enum ScheduleActionType {
  CREATE_SCHEDULE = 'CREATE_SCHEDULE',
  DELETE_SCHEDULE = 'DELETE_SCHEDULE',
  COPIED_SCHEDULE = 'COPIED_SCHEDULE',
  POSITION_CHANGE_SCHEDULE = 'POSITION_CHANGE_SCHEDULE',
  SIZE_CHANGE_SCHEDULE = 'SIZE_CHANGE_SCHEDULE'
}

export default ScheduleActionType